<?php

/**
 * @file
 * Contains easy_slider.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function easy_slider_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the easy_slider module.
    case 'help.page.easy_slider':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A module for creating slider components.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function easy_slider_theme() {
  return [
    'easy_slider_block' => [
      'variables' => [
        'images' => [],
        'captions' => [],
        'settings' => [],
      ],
    ],
  ];
}
